FROM node:10

# Create app directory
WORKDIR /usr/src/app

COPY package.json . /
COPY yarn.lock . /
RUN yarn --prod && yarn cache clean

COPY . .

# Install app dependencies
RUN yarn && yarn global add nodemon && yarn cache clean

ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.3.0/wait /wait
RUN chmod +x /wait

EXPOSE 3000
CMD /wait && yarn startDev
